# Generated by Django 6.0.3 on 2026-04-08 02:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pedidos', '0004_alter_pedido_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(db_index=True, max_length=10, unique=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=45, null=True)),
                ('capacidad_peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacidad_volumen_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_RUTA', 'En Ruta'), ('MANTENIMIENTO', 'Mantenimiento'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'rutas_vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ruta', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PLANIFICADA', 'Planificada'), ('ASIGNADA', 'Asignada'), ('EN_ESPERA', 'En Espera de Inicio'), ('EN_CURSO', 'En Curso'), ('PAUSADA', 'Pausada'), ('DESVIADA', 'Desviada de Ruta'), ('COMPLETADA', 'Completada'), ('PARCIALMENTE_COMPLETADA', 'Parcialmente Completada'), ('CANCELADA', 'Cancelada'), ('POSTERGADA', 'Postergada')], default='BORRADOR', max_length=30)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente'), ('CRITICA', 'Crítica')], default='NORMAL', max_length=20)),
                ('fecha_programada', models.DateField(default=django.utils.timezone.now)),
                ('hora_salida_estimada', models.TimeField(blank=True, null=True)),
                ('hora_retorno_estimada', models.TimeField(blank=True, null=True)),
                ('hora_salida_real', models.TimeField(blank=True, null=True)),
                ('hora_retorno_real', models.TimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hub_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_llegada', to='Pedidos.hub')),
                ('hub_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_salida', to='Pedidos.hub')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='Rutas.vehiculo')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'db_table': 'rutas_ruta',
            },
        ),
        migrations.CreateModel(
            name='ParametrosOptimizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DISTANCIA', 'Minimizar Distancia'), ('TIEMPO', 'Minimizar Tiempo'), ('COSTO', 'Minimizar Costo'), ('COMBINADO', 'Optimización Combinada'), ('MANUAL', 'Manual (sin optimizar)')], default='DISTANCIA', max_length=20)),
                ('ruta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_optimizacion', to='Rutas.ruta')),
            ],
            options={
                'db_table': 'rutas_parametros_optimizacion',
            },
        ),
        migrations.CreateModel(
            name='ParadaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_parada', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('direccion_completa', models.TextField()),
                ('estado', models.CharField(default='PENDIENTE', max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parada_ruta', to='Pedidos.pedido')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='Rutas.ruta')),
            ],
            options={
                'verbose_name': 'Parada de Ruta',
                'verbose_name_plural': 'Paradas de Ruta',
                'db_table': 'rutas_parada_ruta',
            },
        ),
        migrations.CreateModel(
            name='MetricaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_planificada_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('distancia_real_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='Rutas.ruta')),
            ],
            options={
                'db_table': 'rutas_metrica_ruta',
            },
        ),
        migrations.CreateModel(
            name='HistorialCambiosRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_cambiado', models.CharField(max_length=100)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='Rutas.ruta')),
            ],
            options={
                'db_table': 'rutas_historial_cambios',
            },
        ),
        migrations.CreateModel(
            name='AsignacionConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_ruta', to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_conductor', to='Rutas.ruta')),
            ],
            options={
                'db_table': 'rutas_asignacion_conductor',
            },
        ),
        migrations.CreateModel(
            name='AsignacionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_vehiculo', to='Rutas.ruta')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_ruta', to='Rutas.vehiculo')),
            ],
            options={
                'db_table': 'rutas_asignacion_vehiculo',
            },
        ),
        migrations.CreateModel(
            name='ZonaCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('URBANA', 'Zona Urbana'), ('SUBURBANA', 'Zona Suburbana'), ('RURAL', 'Zona Rural'), ('INDUSTRIAL', 'Zona Industrial'), ('COMERCIAL', 'Zona Comercial'), ('RESTRINGIDA', 'Zona Restringida')], default='URBANA', max_length=20)),
                ('centro_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('centro_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('radio_km', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8)),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pedidos.hub')),
            ],
            options={
                'db_table': 'rutas_zona_cobertura',
            },
        ),
    ]
