# Generated by Django 6.0.3 on 2026-04-08 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0004_alter_pedido_usuario'),
        ('Rutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='estado',
            field=models.CharField(blank=True, choices=[('BORRADOR', 'Borrador'), ('PLANIFICADA', 'Planificada'), ('ASIGNADA', 'Asignada'), ('EN_ESPERA', 'En Espera de Inicio'), ('EN_CURSO', 'En Curso'), ('PAUSADA', 'Pausada'), ('DESVIADA', 'Desviada de Ruta'), ('COMPLETADA', 'Completada'), ('PARCIALMENTE_COMPLETADA', 'Parcialmente Completada'), ('CANCELADA', 'Cancelada'), ('POSTERGADA', 'Postergada')], default='BORRADOR', max_length=30),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='hub_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_llegada', to='Pedidos.hub'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='hub_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_salida', to='Pedidos.hub'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente'), ('CRITICA', 'Crítica')], default='NORMAL', max_length=20),
        ),
    ]
