# Generated by Django 6.0.3 on 2026-04-08 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0003_add_direccion_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(help_text='Cliente que solicita el envío', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_modernos', to=settings.AUTH_USER_MODEL),
        ),
    ]
