# Generated by Django 6.0.3 on 2026-04-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0004_alter_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='latitud_destino',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud exacta generada por Geocoding', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='longitud_destino',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud exacta generada por Geocoding', max_digits=9, null=True),
        ),
    ]
