# Generated by Django 6.0.3 on 2026-05-28 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0005_pedido_latitud_destino_pedido_longitud_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_PAGO', 'Pendiente de Pago'), ('PAGO_FALLIDO', 'Pago Fallido'), ('CONFIRMADO', 'Confirmado'), ('EN_PREPARACION', 'En preparación'), ('RECOLECTADO', 'Recolectado'), ('EN_HUB_ORIGEN', 'En hub de origen'), ('EN_TRANSITO', 'En tránsito'), ('EN_HUB_DESTINO', 'En hub de destino'), ('EN_REPARTO', 'En reparto'), ('ENTREGADO', 'Entregado'), ('INTENTO_FALLIDO', 'Intento fallido'), ('DEVUELTO', 'Devuelto'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=30),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wompi_tx_id', models.CharField(max_length=100, unique=True, verbose_name='ID de Transacción Wompi')),
                ('metodo', models.CharField(choices=[('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('PSE', 'PSE / Cuenta de Ahorros'), ('NEQUI', 'Nequi'), ('BANCOLOMBIA_TRANSFER', 'Transferencia Bancolombia'), ('EFECTIVO', 'Efectivo / Corresponsal')], default='TARJETA_CREDITO', max_length=30)),
                ('estado', models.CharField(choices=[('APPROVED', 'Aprobado'), ('DECLINED', 'Declinado'), ('ERROR', 'Error en Transacción'), ('PENDING', 'Pendiente')], default='PENDING', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto cobrado en COP', max_digits=12)),
                ('referencia', models.CharField(help_text='Referencia única generada por Enviart', max_length=100, unique=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('detalles_adicionales', models.JSONField(blank=True, help_text='Campos extras de Wompi', null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='Pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pedidos_pago',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
