# Generated by Django 6.0.3 on 2026-06-05 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0007_historialubicacion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='historialubicacion',
            new_name='pedidos_his_pedido__58d089_idx',
            old_name='pedidos_his_pedido__a1b2c3_idx',
        ),
    ]
