# Generated by Django 6.0.3 on 2026-06-14 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0008_rename_pedidos_his_pedido__a1b2c3_idx_pedidos_his_pedido__58d089_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventotracking',
            name='evidencia_documento',
            field=models.FileField(blank=True, null=True, upload_to='tracking/documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt'])]),
        ),
        migrations.AlterField(
            model_name='guiaenvio',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='PDF de la guía para descarga', null=True, upload_to='guias/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='pruebaentrega',
            name='firma_digitizada',
            field=models.ImageField(help_text='Firma capturada en dispositivo móvil', upload_to='pod/firmas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='pruebaentrega',
            name='foto_frente',
            field=models.ImageField(blank=True, help_text='Foto del frente del inmueble (opcional)', null=True, upload_to='pod/fotos/frente/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='pruebaentrega',
            name='foto_paquete',
            field=models.ImageField(help_text='Foto del paquete en lugar de entrega', upload_to='pod/fotos/paquete/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
