# Generated by Django 6.0.3 on 2026-03-29 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_novedad', models.DateTimeField()),
                ('tipo_novedad', models.CharField(choices=[('ACTUALIZACION', 'Actualización'), ('INCIDENCIA', 'Incidencia'), ('ENTREGA', 'Entrega'), ('OTRO', 'Otro')], max_length=30)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='Pedidos.Pedido')),
                ('usuario', models.ForeignKey(help_text='Usuario que registró la novedad', on_delete=django.db.models.deletion.PROTECT, related_name='novedades_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Novedad de Pedido',
                'verbose_name_plural': 'Novedades de Pedido',
                'db_table': 'novedad_pedido',
                'ordering': ['-fecha_novedad'],
            },
        ),
    ]
