# Generated by Django 6.0.3 on 2026-06-14 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novedades', '0002_categorianovedad_metricanovedad_novedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencianovedad',
            name='archivo',
            field=models.FileField(max_length=255, upload_to='novedades/evidencias/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'pdf', 'doc', 'docx', 'mp4'])]),
        ),
    ]
