[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m daphne -b 0.0.0.0 -p $PORT config.asgi:application"
healthcheckPath = "/api/auth/login/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[environment]
DJANGO_SETTINGS_MODULE = "config.settings.railway"
