# Generated by Django 6.0.3 on 2026-04-03 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nombre_corto', models.CharField(help_text='Nombre común', max_length=50)),
                ('codigo_iso2', models.CharField(help_text='Código ISO 3166-1 alpha-2', max_length=2, unique=True)),
                ('codigo_iso3', models.CharField(help_text='Código ISO 3166-1 alpha-3', max_length=3, unique=True)),
                ('codigo_telefono', models.CharField(help_text='Ej: +57 para Colombia', max_length=10)),
                ('moneda', models.CharField(default='COP', help_text='Código ISO 4217', max_length=3)),
                ('requiere_departamento', models.BooleanField(default=True, help_text='¿Requiere estado/departamento?')),
                ('requiere_codigo_postal', models.BooleanField(default=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('codigo_tributario', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'ubicaciones_pais',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo_iso2'], name='ubicaciones_codigo__0aff73_idx'), models.Index(fields=['es_activo'], name='ubicaciones_es_acti_bf62ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, help_text='Código interno', max_length=20, null=True)),
                ('codigo_iso', models.CharField(blank=True, help_text='Código ISO 3166-2', max_length=10, null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='Ubicaciones.pais')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'ubicaciones_departamento',
                'ordering': ['pais', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('es_capital', models.BooleanField(default=False)),
                ('es_activo', models.BooleanField(default=True)),
                ('zona_envio', models.CharField(blank=True, help_text='Zona para tarifación (ej: ZONA1, ZONA2)', max_length=50, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='Ubicaciones.departamento')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ubicaciones_ciudad',
                'ordering': ['departamento', 'nombre'],
                'indexes': [models.Index(fields=['departamento', 'es_activo'], name='ubicaciones_departa_7da3c4_idx'), models.Index(fields=['zona_envio'], name='ubicaciones_zona_en_12ee7f_idx')],
                'unique_together': {('departamento', 'nombre')},
            },
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['pais', 'es_activo'], name='ubicaciones_pais_id_943ab4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('pais', 'nombre')},
        ),
    ]
