# Generated by Django 6.0.3 on 2026-04-04 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo_hub', models.CharField(help_text='Código único del hub', max_length=10, unique=True)),
                ('tipo_hub', models.CharField(choices=[('PRINCIPAL', 'Hub Principal'), ('SECUNDARIO', 'Hub Secundario'), ('TEMPORAL', 'Hub Temporal'), ('PARTNER', 'Hub de Partner')], default='PRINCIPAL', max_length=20)),
                ('direccion', models.CharField(help_text='Dirección completa del hub', max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('capacidad_operativa', models.PositiveIntegerField(default=1000, help_text='Capacidad operativa diaria (paquetes)')),
                ('horario_operacion', models.CharField(default='08:00-18:00', help_text='Horario de operación', max_length=100)),
                ('servicios_disponibles', models.JSONField(default=dict, help_text='Servicios disponibles en el hub')),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hubs', to='Ubicaciones.ciudad')),
            ],
            options={
                'verbose_name': 'Hub',
                'verbose_name_plural': 'Hubs',
                'db_table': 'hubs',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo_hub'], name='hubs_codigo__da855e_idx'), models.Index(fields=['ciudad'], name='hubs_ciudad__ffd631_idx'), models.Index(fields=['tipo_hub'], name='hubs_tipo_hu_3bd579_idx'), models.Index(fields=['es_activo'], name='hubs_es_acti_7dce1a_idx')],
            },
        ),
    ]
