# Generated by Django 6.0.3 on 2026-04-04 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ubicaciones', '0002_hub'),
        ('Ubicaciones', '0002_initial_data'),
    ]

    operations = [
    ]
