# Generated by Django 6.0.3 on 2026-04-02 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('tipo_rol', models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('USUARIO', 'Usuario'), ('MENSAJERO', 'Mensajero'), ('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor')], max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del rol')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['nombre_rol'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PP', 'Pasaporte'), ('NIT', 'NIT')], default='CC', max_length=10)),
                ('doc_usuario', models.CharField(db_index=True, max_length=25, unique=True)),
                ('primer_nombre', models.CharField(max_length=80)),
                ('segundo_nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('primer_apellido', models.CharField(max_length=80)),
                ('segundo_apellido', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('two_factor_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('intentos_login_fallidos', models.PositiveIntegerField(default=0)),
                ('bloqueo_hasta', models.DateTimeField(blank=True, null=True)),
                ('ultimo_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='Autenticacion.rol')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'indexes': [models.Index(fields=['email'], name='usuarios_email_0ff7b3_idx'), models.Index(fields=['doc_usuario'], name='usuarios_doc_usu_e737c4_idx'), models.Index(fields=['is_active', 'is_staff'], name='usuarios_is_acti_13114d_idx')],
            },
        ),
    ]
