# Generated by Django 6.0.3 on 2026-04-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='tipo_rol',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('MENSAJERO', 'Mensajero'), ('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor')], max_length=50, null=True),
        ),
    ]
