# Generated by Django 6.0.3 on 2026-06-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0002_alter_rol_tipo_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='two_factor_enabled',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='two_factor_secret',
        ),
        migrations.AddField(
            model_name='usuario',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
