# Generated by Django 6.0.3 on 2026-06-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0003_remove_usuario_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='tipo_rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('MENSAJERO', 'Mensajero'), ('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor')], default='CLIENTE', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PP', 'Pasaporte'), ('NIT', 'Número de Identificación Tributaria (NIT)')], default='CC', max_length=10),
        ),
    ]
