# Generated by Django 6.0.3 on 2026-07-02 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0004_alter_rol_tipo_rol_alter_usuario_tipo_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='totp_enabled',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='totp_secret',
        ),
    ]
